export const sample_foods = [
  {
    id: "1",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: true,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "3",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "4",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "5",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "6",
    name: "Pizza Peperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_users = [
  {
    id: 1,
    name: "Dragos Paizan",
    email: "dragos@gmail.com",
    password: "12345",
    address: "Iasi",
    isAdmin: true,
  },
];
